- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Updating apt
      command: sudo apt-get update

    - name: Install Docker
      command: sudo apt-get install -y docker.io

    - name: Start Docker Service
      command: sudo systemctl start docker

    - name: Stop existing container if running
      shell: |
        docker ps -q --filter "ancestor=abhiz2411/bankapp1" | grep -q . && docker stop $(docker ps -q --filter "ancestor=abhiz2411/bankapp1") || true

    - name: Remove existing container if stopped
      shell: |
        docker ps -a -q --filter "ancestor=abhiz2411/bankapp1" | grep -q . && docker rm $(docker ps -a -q --filter "ancestor=abhiz2411/bankapp1") || true

    - name: Deploy Docker Container
      command: docker run -itd -p 8084:8081 abhiz2411/bankapp1
